name: First WorkFlow
on: [push]     # events


jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello"
      - name: Mutileline run-shell-commands
        run: |
          node -v
          pwd  
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: view software verion
        run: sw_vers
  dependant-job:
    runs-on: windows-lates
    needs: run-shell-commands  
    steps:  
      - name: echo a string 
        run: Write-Ouput "windows String"
      - name: Error steps
        run: doesnotexits 