name: working Dirs & Shells
on: [push]
defaults:
    run:
       shell: bash 
       #working-directory: /de/ed    # overwriting working directory 
jobs:
    display-wd-info-linux:
        runs-on: ubuntu-latest
        steps:
            - name: Display working directory & List the files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
            - name: Change working directory
              working-directory: /home/runner
              run: pwd
                 
    display-wd-info-windows:
        runs-on: windows-latest
        defaults:
            run:
               shell: pwsh 
        steps:
            - name: Display working directory & List the files
              run: |
                Get-Location
                dir
                echo $env:GITHUB_SHA
                echo $env:GITHUB_REPOSITORY
                echo $env:GITHUB_WORKSPACE  
            - name: Python shell
              shell: python
              run: |
                import platform
                print(platform.processor())

                       

